version: '3'

services:
  linuxdev:
    build: .
    image: devenv:linuxdev
    container_name: linux_development
    hostname: linux_development
    volumes:
      - ${Relative_Mount}:/mnt/host_files
    stdin_open: true
    tty: true
