version: '3'

services:
  linuxdev:
    build: .
    image: linuxdev:centos_bash
    container_name: linuxdev
    hostname: linuxdev
    volumes:
      - ${Relative_Mount}:/mnt/host_files
    stdin_open: true
    tty: true
